---
- hosts : tag_Name_Production_ubuntu
  become: yes 
  tasks:
  - name: Enabling the npm repository 
    shell: curl -sL https://deb.nodesource.com/setup_14.x
#  - name: logining in as root  
#    command: sudo su -
  - name: caching the apt
    apt:
      update_cache: yes     
  - name: installing the packages
    apt: 
      name: "{{item}}"
      state: present
    with_items:
      - mongodb
      - nodejs
      - gcc
      - g++
      - make
      - git
      - npm
  - name: Start and enable mongodb service 
    service: 
      name: mongodb
      state: started
      enabled: yes
  - name: Installing yarn and gulp via NPM
    npm:
      name: "{{item}}"
      global: yes
      state: present
    with_items:
      - yarn
      - gulp
  - name: Git cloning mean repository 
    git:
      repo: https://github.com/meanjs/mean
      clone: yes
      dest: /home/ubuntu/mean
  - name: Moving to the MeanJS directory and installing the necessary packages for Mean Stack
    shell: |
      cd /home/ubuntu/mean
      yarn install 
    register: output
  - name: output debug info
    debug: 
      var: output.stdout_lines 
  - name: Copying the server.js file 
    template: 
      src: /opt/Terraform/webserver/server.js.j2
      dest: /home/ubuntu/mean/server.js
      mode: 744
      owner: ubuntu
      group: ubuntu
  - name: starting the mean service for checking if it works 
    shell: gulp 
########################################################################################